### ISSUE TITLE
HODL Program : Unable to authenticate with the HODL server

### ISSUE THREAD

**Issue by PrEzi3** [HDDcoin-Network/hddcoin-blockchain#13]
### What happened?

After upgrade to the newest 1.2.11 I wanted to check out HODL Program. 
I am doing it from the official Windows GUI in the HODL section.  
However there is already problem at the very first step :
after entering passphrase and doing "hddcoin hodl programs" I always get 
"Connection error: Unable to authenticate with the HODL server."

![image](https://user-images.githubusercontent.com/33815762/148379488-f038be15-3574-4746-bffa-237586922c3d.png)

My clock is syncing every 2 hours using the EU Timepool servers, so this is definitely not the issue here... 
(Also same errors when doing this directly from the CLI.)

P.S. Why we cannot use copy + paste in the HODL "GUI" ?  even ctrl+shift+v (*nix CLI paste) produces weird results...

### Version

1.2.11

### What platform are you using?

Windows

### What ui mode are you using?

GUI

**Comment by rwarren** [comment]
HODL server communications were a server-side issue prior to HODL being launched. This is no longer an issue.

P.S.  Copy-paste in the GUI terminal is a known issue and is coming soon.

**Comment by PrEzi3** [comment]
Thanks !  checked again and this time the server replies. Then it seems I need to wait till the HODL Programs are live now.
Glad you are aware of the copy + paste problem --- if you have a long passphrase this is extremely ... suboptimal...
