### ISSUE TITLE
Where is the rest 1.75 [BUG]

### ISSUE THREAD

**Issue by Blackcode** [HDDcoin-Network/hddcoin-blockchain#7]
Had a win but only 0.25 is shown in the walled. Where is the rest 1.75?

**Comment by jdoerrer** [comment]
If you are using NFT Plots like I am, soloing mining.. then you have to wait one week to use the NFT recovery tool. to get the rest.  Only using OG plots mining will get you full reward and allowing you to mine on Foxypool.io with the OG plots.  Using https://alltheblocks.net/nft-recovery   with your chia contract ID after one week from time you found block will the reset be sent to your wallet but you have to manually recover it.  i think this is do to the way contract works for chia. Anyone can correct me if I am wrong.

**Comment by jdoerrer** [comment]
Also you can visit there discord for any questions on HDD to get a better technical explanation.  Link to Discord https://discord.gg/R62q58bHZq

**Comment by Blackcode** [comment]
ok tnx
